name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest
      
    - name: Convert line endings (dos2unix)
      run: sudo apt-get install -y dos2unix && dos2unix deploy.sh

    - name: Make deploy.sh executable
      run: chmod +x deploy.sh

    - name: Deploy the app
      run: ./deploy.sh

    - name: Make health_check.sh executable
      run: chmod +x health_check.sh

    - name: Make rollback.sh executable
      run: chmod +x rollback.sh

    - name: Run Health Check
      run: |
        ./health_check.sh
        # Check if health_check.sh returned 200 (success)
        if grep -q "App is NOT running" health.log; then
          echo "Health check failed, rolling back deployment..."
          # Rollback to previous version 
          ./rollback.sh
          exit 1  # Fail the job if rollback happens
        else
          echo "Health check passed."
        fi

    
