name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Check if deploy.sh exists
      run: |
        ls -l deploy.sh  # List the file and permissions
        cat deploy.sh    # Optionally, print the contents of the script


    - name: Deploy app
      run: |
        # Deploy the app 
        chmod +x deploy.sh
        ./deploy.sh
        
    - name: Run Health Check
      run: |
        ./health_check.sh
        # Check if health_check.sh returned 200 (success)
        if grep -q "App is NOT running" health.log; then
          echo "Health check failed, rolling back deployment..."
          # Rollback to previous version (adjust based on your rollback strategy)
          ./rollback.sh
          exit 1  # Fail the job if rollback happens
        else
          echo "Health check passed."
        fi
