name: CI/CD with Rollback

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Deploy to server
      if: success()
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST 'bash ~/deploy.sh'

    - name: Run health check
      if: success()
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        STATUS=$(ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST 'bash ~/health_check.sh && tail -n 1 ~/health.log')

        echo "Health check result: $STATUS"

        if [[ "$STATUS" == *"NOT running"* ]]; then
          echo "Health check failed. Triggering rollback..."
          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST 'bash ~/rollback.sh'
          exit 1
        fi
